name: Build papers.json from sources
on:
  push:
    paths:
      - 'data/sources.csv'
      - 'data/overrides.json'
      - 'scripts/build_papers.py'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Build papers.json
        run: python scripts/build_papers.py
      - name: Commit & push papers.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-build papers.json"
          file_pattern: data/papers.json
